### PR TITLE
Move operator

### PR DESCRIPTION
**Pull request by dweber019**
As discussed in https://github.com/Apicurio/apicurio-registry/issues/1215 I move the operator into this repository.
I changed the domain to apicuio.io too.

Have a look and feedback always welcome ;)

### CODE REVIEW

**Comment by EricWittmann** [comment]
We'll probably want to upgrade this to be registry 2.0 compliant basically immediately.  :) :)

**Comment by dweber019** [comment]
Nice, I can support if you like?

**Comment by famartinrh** [comment]
it would be nice to at least merge this code so we will have "support" for the 1.3.2.Final version, and later update to support the 2.0 version.

Btw I would like take a look at the code but I'm a bit busy atm, so if you don't mind, can we wait a couple of days before merging please

**Comment by jsenko** [comment]
The only immediate thing that I see is that we need update the workflow `.github/workflows/main.yml` and image references, since we moved to use `quay.io`. i.e.
`docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" "quay.io"`
and
`docker.io/apicurio/apicurio-registry-content-sync-operator:v0.0.1` -> `quay.io/apicurio/apicurio-registry-content-sync-operator:v0.0.1`

**Review by famartinrh — CHANGES_REQUESTED** [review]
LGTM, overall it's nice, we can work later on adapting this to Apicurio Registry 2.0 or any other design changes we may think of.

The only change I think is needed for now is what Jakub mentioned... we moved the operator images to quay so it would be nice to move this operator to quay as well

**Comment by EricWittmann** [comment]
OK great ... who will do that?  :)

**Comment by famartinrh** [comment]
done, once merged to the PRs branch we should be set up

**Comment by dweber019** [comment]
Is there anything needed from my side?

**Comment by EricWittmann** [comment]
So it turns out that we have some internal requirements that were very similar to what you've done with the golang operator, but we've been encouraged to use Quarkus where possible.  As a result, @famartinrh has recreated the functionality (and some additional functionality) in a new Java based operator here:

https://github.com/Apicurio/apicurio-registry-content-sync-operator/pull/2

If you had some time to take a look and give us your opinion whether that operator would satisfy your requirements, that would be super helpful!

**Comment by dweber019** [comment]
Hehe redhat 😄
I just had a quick look and the external content is the only thing missing for me.

**Pull request closed without merging**
